### ISSUE TITLE
[Feature]: Make Navbar for each of the html pages other than the Home Page.

### ISSUE THREAD

**Issue by Prayas248** [OPCODE-Open-Spring-Fest/units-converter#1]
### So, what is it about?

Replicate the Navbar present at the Home Page (which is index.html file) for all HTML files present in the "HTML" folder.

Make sure that you replicate the Navbar present in index.html.

Also apply the same CSS.
Make a common stylesheet for navbar which you would link with each of the mentioned HTML files

Make sure to contact me for any difficulty regarding not understanding the issue before sending any Pull Request.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nidhi-Satyapriya** [comment]
Kindly assign this to me.

**Comment by Prayas248** [comment]
> Kindly assign this to me.


- Ok you will be assigned this issue
- you have 2 days from tomorrow to submit the PR for this issue
- For any issue related queries, do contact me on Discord

**Comment by rohityadav74** [comment]
@Prayas248 please assign it to me. I have the necessary skills to do this. I will do it in a very efficient manner. I will follow the code of conduct.

**Comment by SAURABHM6341** [comment]
@Prayas248 kindly assign this issue to me. I have understood the issue and will solve it.

**Comment by Sidd2004Shukla** [comment]
@Prayas248  please assign this to me

**Comment by pooja030406** [comment]
please assign this task to me

**Comment by pooja030406** [comment]
@Prayas248 please assign this task to me

**Comment by eddy1112004** [comment]
@Prayas248 please assign this to me.

**Comment by neerajyadavrewa** [comment]
@Prayas248 please assign this issue  to me
