### ISSUE TITLE
[Feature]: Make the Navbar more stylish and show that which page is currently active.

### ISSUE THREAD

**Issue by Prayas248** [OPCODE-Open-Spring-Fest/units-converter#2]
### So, what is it about?

Apply CSS to Navbar present in index.html file which is:
- More stylish and if possible a bit animated.
- Responsive.
- Should show which page is currently active.

Make sure that changes that you make is applicable on all the rest of the html files present in the "HTML" folder.

Make sure to contact me for any difficulty regarding not understanding the issue before sending any Pull Request.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jagpreet153** [comment]
@Prayas248 Please assign this task to me

**Comment by Prayas248** [comment]
> @Prayas248 Please assign this task to me


> * Ok you will be assigned this issue
> * you have 4 days from tomorrow to submit the PR for this issue
> * For any issue related queries, do contact me on Discord

**Comment by princekumar39** [comment]
@Prayas248  assign this task to me

**Comment by princekumar39** [comment]
@Prayas248 assign this task to me please
