### ISSUE TITLE
[Feature]: Creation of Home Page

### ISSUE THREAD

**Issue by Prayas248** [OPCODE-Open-Spring-Fest/units-converter#3]
### So, what is it about?

- The Home page should be made in the file "index.html" below the Navbar where "This is the Home Page" is currently being displayed (Note that you have to replace the text "This is the Home Page" as it is only for your reference).

- Home Page should contain the basic information about the different type of units that are currently being used ( for eg- for currency, mention about Indian Rupee, USD, Pounds and Euro, similarly for the rest) and what this site does (that is, convert one type of currency to another in case of currency converion, similarly for others etc.).
- Appropriate CSS should be applied to make it look a bit professional, also it should be responsive.
- A separate stylesheet should be linked toindex.html file, named - "HomePage.css" which should be present in the "CSS" folder.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by instantboostbyabhaykeshari** [comment]
@Prayas248  Kindly assigned this task to me to solve the given issue. I have descent knowledge of required programing language.

**Comment by Prayas248** [comment]
> @Prayas248 Kindly assigned this task to me to solve the given issue. I have descent knowledge of required programing language.


- Ok you will be assigned this issue
- you have 4 days from tomorrow to submit the PR for this issue
- For any issue related queries, do contact me on Discord

**Comment by princekumar39** [comment]
ASSIGN this issue to me for better homepage layout please @Prayas248

**Comment by Prayas248** [comment]
> ASSIGN this issue to me for better homepage layout please @Prayas248


- Ok you will be assigned this issue
- you have 4 days from today to submit the PR for this issue
- For any issue related queries, do contact me on Discord

- Whoever would do it better would get the point.
- If one submits, then i will wait for the other one to submit for one day, if the other person submits before that, then he will be considered, otherwise the first person would get point (if the work satisfies the issue).

**Comment by Prayas248** [comment]
> ASSIGN this issue to me for better homepage layout please @Prayas248

Ok you will also be assigned this issue

**Comment by pooja030406** [comment]
@Prayas248 please assign this task to me

**Comment by neerajyadavrewa** [comment]
@Prayas248 please assign this to me

**Comment by Prayas248** [comment]
> @Prayas248 please assign this task to me

You are assigned this issue

**Comment by Prayas248** [comment]
> @Prayas248 please assign this to me

You are assigned this issue
