### ISSUE TITLE
[Feature]: Apply CSS to the file "volume.html".

### ISSUE THREAD

**Issue by Prayas248** [OPCODE-Open-Spring-Fest/units-converter#6]
### So, what is it about?

- Apply CSS to the file "volume.html" which is present inside the folder named "HTML".
- The stylesheet used should be "volume.css" which is already present inside the folder named "CSS".
- The stylesheet should be linked with "volume.html" file.
- The CSS applied should make the page look more professional.
- The CSS applied should also be responsive.
- NOTE: if any of the pages other than this file already has CSS, then try to make the theme of your CSS similar with that for uniformity.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sanyam-15** [comment]
@Prayas248 please assign me this task ,i can solve it.

**Comment by Prayas248** [comment]
> @Prayas248 please assign me this task ,i can solve it.

> * Ok you will be assigned this issue
> * you have 4 days from tomorrow to submit the PR for this issue
> * For any issue related queries, do contact me on Discord

**Comment by theBcap** [comment]
@Prayas248 sir please assign this task to me.

**Comment by Prayas248** [comment]
@sanyam-15 completed this issue.
