### ISSUE TITLE
[Feature]: Apply CSS to the file "weight.html".

### ISSUE THREAD

**Issue by Prayas248** [OPCODE-Open-Spring-Fest/units-converter#7]
### So, what is it about?

- Apply CSS to the file "weight.html" which is present inside the folder named "HTML".
- The stylesheet used should be "weight.css" which is already present inside the folder named "CSS".
- The stylesheet should be linked with "weight.html" file.
- The CSS applied should make the page look more professional.
- The CSS applied should also be responsive.
- NOTE: if any of the pages other than this file already has CSS, then try to make the theme of your CSS similar with that for uniformity.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nishant05092** [comment]
@Prayas248 kindly assign me this issue to solve.

**Comment by lokesh2201013** [comment]
could you please assign this to me

**Comment by Prayas248** [comment]
> @Prayas248 kindly assign me this issue to solve.

> * Ok you will be assigned this issue
> * you have 2 days from tomorrow to submit the PR for this issue
> * For any issue related queries, do contact me on Discord

**Comment by Prayas248** [comment]
> could you please assign this to me

> * Ok you will be assigned this issue
> * you have 2 days from tomorrow to submit the PR for this issue
> * For any issue related queries, do contact me on Discord

**Comment by Sidd2004Shukla** [comment]
@Prayas248 please assign this to me.

**Comment by eddy1112004** [comment]
@Prayas248 please assign this to me.

**Comment by neerajyadavrewa** [comment]
@Prayas248 please assign this to me

**Comment by Prayas248** [comment]
> @Prayas248 please assign this to me.

You are assigned this issue

**Comment by Prayas248** [comment]
> @Prayas248 please assign this to me

You are assigned this issue
